import { useState, useEffect } from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'

import Image from 'next/image'
import Dashboardstyle from '../styles/Dashboard.module.css'
import { useRouter } from 'next/router'

import { FiChevronRight, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from "react-icons/fi";
import Link from 'next/link'

const Dashboard = ({ SetHeader_true }) => {
    SetHeader_true(false)
    const router = useRouter()
    const [UserlogData, setUserlogData] = useState();
    useEffect(() => {
        try {
            if (localStorage.getItem('userid')) {

                const usermobnow = localStorage.getItem('userid');
                const sendUser = { usermobnow }
                const data = fetch("/api/check", {
                    method: "POST",
                    headers: {
                        'Content-type': 'application/json'
                    },
                    body: JSON.stringify(sendUser)
                }).then((a) => {
                    return a.json();
                })
                    .then((parsedUser) => {
                        // console.log(parsedUser.data)
                        setUserlogData(parsedUser.data.name)
                    })

            } else {
                router.push('/')
            }
        } catch (error) {
            console.error(error)
            router.push('/')

        }
        // check login credential end

    }, [router.query]);


    return (
        <>
            <Head>
                <title>My Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.DashboardBox}>
                    <div className={styles.Welcomeuserbox}>
                        <span>Hi👋 {UserlogData}</span>
                    </div>
                    <div className={styles.Countbox}>
                        <div className={styles.CountboxItem} style={{ backgroundColor: '#efecff' }}>
                            <div className={styles.CountboxItemText}>
                                <small>Lavel</small>
                                <span>10K+</span>
                            </div>
                            <div className={styles.CountboxItemImg}>
                                <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/job.webp' height={75} width={75} />
                            </div>
                        </div>
                        <div className={styles.CountboxItem} style={{ backgroundColor: '#fff6e9' }}>
                            <div className={styles.CountboxItemText}>
                                <small>Attempts</small>
                                <span>30</span>
                            </div>
                            <div className={styles.CountboxItemImg}>
                                <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/hiring.webp' height={75} width={75} />
                            </div>
                        </div>
                        <div className={styles.CountboxItem} style={{ backgroundColor: '#ffe9f1' }}>
                            <div className={styles.CountboxItemText}>
                                <small>Points
                                </small>
                                <span>4000</span>
                            </div>
                            <div className={styles.CountboxItemImg}>
                                <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/salary.webp' height={75} width={75} />
                            </div>
                        </div>
                        <div className={styles.CountboxItem} style={{ backgroundColor: '#dcf9fd' }}>
                            <div className={styles.CountboxItemText}>
                                <small>Enrolled</small>
                                <span>1</span>
                            </div>
                            <div className={styles.CountboxItemImg}>
                                <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/worth.webp' height={75} width={75} />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Dashboard
