import { useState, useEffect } from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'
import TextField from '@mui/material/TextField';
import Image from 'next/image'
import Dashboardstyle from '../styles/Dashboard.module.css'
import { useRouter } from 'next/router'
import { FiChevronRight, FiNavigation, FiInfo, FiCoffee, FiFileText, FiClock, FiUnlock, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from 'react-icons/fi';

import Link from 'next/link'

const MyAccount = () => {
  
    const router = useRouter()
    const [UserName, setUserName] = useState('');
    const [UserMobile, setUserMobile] = useState('');
    const [UserEmail, setUserEmail] = useState('');
    const [UserlogData, setUserlogData] = useState();
    const [Retdata, setRetdata] = useState([]);
    const handleChangeMob = () => {
        const mobA = document.querySelector('#userm').value

    }
    useEffect(() => {

        try {
            if (localStorage.getItem('userid')) {

                const usermobnow = localStorage.getItem('userid');
                const sendUser = { usermobnow }
                const data = fetch("/api/check", {
                    method: "POST",
                    headers: {
                        'Content-type': 'application/json'
                    },
                    body: JSON.stringify(sendUser)
                }).then((a) => {
                    return a.json();
                })
                    .then((parsedUser) => {
                        console.log(parsedUser.data.name)
                        setUserName(parsedUser.data.name)
                        setUserMobile(parsedUser.data.mobile)
                        setUserEmail(parsedUser.data.email)


                    })

            } else {

            }
        } catch (error) {

        }
        // check login credential end

    }, [router.query]);

    return (
        <>
            <Head>
                <title>My Account</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.DashboardBox}>
                    <div className={styles.Welcomeuserbox}>
                        <span>Profile</span>
                    </div>
                    <div className={styles.DbTowBox}>
                        <div className={styles.DbTowBoxA}>
                            <div className={styles.DPIMG}>
                                <img src='https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png' alt='dp' width='100%' />
                            </div>
                        </div>
                        <div className={styles.DbTowBoxB}>
                            <div style={{ fontWeight: 'bold' }}>
                                <span>Edit Your profile :</span>
                            </div>

                            <div className={styles.EditAccInput}>
                                <TextField fullWidth label="Name" id="userm" onChange={handleChangeMob} value={UserName} />
                            </div>
                            <div className={styles.EditAccInput}>
                                <TextField fullWidth label="Mobile Number" id="userm" onChange={handleChangeMob} value={UserMobile} />
                            </div>
                            <div className={styles.EditAccInput}>
                                <TextField fullWidth label="Email ID" id="userm" onChange={handleChangeMob} value={UserEmail} />
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </>
    )
}

export default MyAccount
