import { useState, useEffect } from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'
import PlayQuiz from '../components/PlayQuiz'

import { useRouter } from 'next/router'
import { FiChevronRight, FiNavigation, FiInfo, FiCoffee, FiFileText, FiClock, FiUnlock, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from 'react-icons/fi';

import Link from 'next/link'

const Mytest = ({ ID }) => {
    const router = useRouter()
    const [isLoading, setIsLoading] = useState(true);
    const [Retdata, setRetdata] = useState([]);
    useEffect(() => {

        try {
            if (localStorage.getItem('userid')) {

               
                const TestID = { ID }
                const data = fetch("/api/TestChaptersList", {
                    method: "POST",
                    headers: {
                        'Content-type': 'application/json'
                    },
                    body: JSON.stringify(TestID)
                }).then((a) => {
                    return a.json();
                })
                    .then((parsedUser) => {
                        // console.log(parsedUser)
                        setRetdata(parsedUser)
                        setIsLoading(false)
                    })

            } else {

            }
        } catch (error) {
            console.error(error)


        }
        // check login credential end

    }, [router.query]);


    return (
        <>
            <Head>
                <title>{ID} : Test Series Chapters</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.DashboardBox}>
                    {isLoading &&
                        <div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                        </div>
                    }
                    {!isLoading &&
                    <div>
                            {Retdata.map((item) => {
                                return <div className={styles.testboxtestlist} key={item.id}>
                                    <div className={styles.testboxtestlistA} >
                                        <div className={styles.Testlistitem}>

                                            <div className={styles.Testlistitems}>

                                                <div> <span>{item.title}</span></div>
                                                <div className={styles.testiconsBox}>
                                                    <div className={styles.testiconsItemMain}>
                                                        <span><FiCoffee /></span>   <span>{item.PerQMarks} Questions</span>
                                                    </div>
                                                    <div className={styles.testiconsItemMain}>
                                                        <span><FiFileText /></span>   <span>{item.totalMarks} Marks</span>
                                                    </div>
                                                    <div className={styles.testiconsItemMain}>
                                                        <span><FiClock /></span>   <span>{item.duration} Mins</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <PlayQuiz Pid={item.pid} ChapterName={item.title} ChapterID={item.id} duration={item.duration} totalMarks={item.totalMarks} Totalques={item.PerQMarks} RulesTest={item.RulesTest} />

                                        </div>

                                    </div>

                                </div>
                            }

                            )}
                        </div>
                    }
                    
                </div>
            </div>
        </>
    )
}

export default Mytest
