import { useState, useEffect } from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'
import PlayQuiz from '../components/PlayQuiz'
import Image from 'next/image'
import Dashboardstyle from '../styles/Dashboard.module.css'
import { useRouter } from 'next/router'
import { FiChevronRight, FiNavigation, FiInfo, FiCoffee, FiFileText, FiClock, FiUnlock, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from 'react-icons/fi';

import Link from 'next/link'

const Mytest = ({ SetHeader_true, ID }) => {
    SetHeader_true(false)
    const router = useRouter()
    const [UserlogData, setUserlogData] = useState();
  
    const [Retdata, setRetdata] = useState([]);
    useEffect(() => {

        try {
            if (localStorage.getItem('userid')) {

                const usermobnow = localStorage.getItem('userid');
                const userid = { usermobnow }
                const TestID = { ID }
                const data = fetch("/api/TestChaptersList", {
                    method: "POST",
                    headers: {
                        'Content-type': 'application/json'
                    },
                    body: JSON.stringify(TestID)
                }).then((a) => {
                    return a.json();
                })
                    .then((parsedUser) => {
                        console.log(parsedUser)
                        setRetdata(parsedUser)
                    })

            } else {

            }
        } catch (error) {
            console.error(error)


        }
        // check login credential end

    }, [router.query]);


    return (
        <>
            <Head>
                <title>{ID} : Test Series Chapters</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.DashboardBox}>
                    <div className={styles.Welcomeuserbox}>
                        <span>{ID} Chapters</span>
                    </div>

                    {Retdata.map((item) => {
                        return <div className={styles.testboxtestlist} key={item.id}>
                            <div className={styles.testboxtestlistA} >
                                <div className={styles.Testlistitem}>

                                    <div className={styles.Testlistitems}>

                                        <div> <span>{item.title}</span></div>
                                        <div className={styles.testiconsBox}>
                                            <div className={styles.testiconsItemMain}>
                                                <span><FiCoffee /></span>   <span>100 Questions</span>
                                            </div>
                                            <div className={styles.testiconsItemMain}>
                                                <span><FiFileText /></span>   <span>100 Marks</span>
                                            </div>
                                            <div className={styles.testiconsItemMain}>
                                                <span><FiClock /></span>   <span>60 Mins</span>
                                            </div>
                                        </div>
                                    </div>
                                    <PlayQuiz Pid={item.pid} ChapterName={item.title} />

                                </div>

                            </div>

                        </div>
                    }

                    )}
                </div>
            </div>
        </>
    )
}

export default Mytest
