import Login from '../components/Login'
import { useState, useEffect } from 'react'
import { useRouter, Router } from 'next/router'
import '../styles/globals.css'
import Navbar from '../components/Navbar'
import SubNavbar from '../components/SubNavbar'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'

import LoadingBar from 'react-top-loading-bar'
import Head from 'next/head'
import Backdropitem from '../components/Backdropitem'
function MyApp({ Component, pageProps }) {
  const router = useRouter()
  const [progress, setProgress] = useState(0);
  const [openModal, setOpenmodal] = useState(false);
  const [subheader, setSubheader] = useState(false);
  const [BackDropData, setBackDrop] = useState(false);
  const handleOpen = () => setOpenmodal(true);
  const handleClose = () => setOpenmodal(false);
  const [userlogst, setUserlogst] = useState(false);
  const [userlogData, setUserlogData] = useState();



  const BackDropOpen = () => {
    setBackDrop(true)
  }
  
  const BackDropClose = () => {
    setBackDrop(false)
  }
  
  const SetHeader_true = () => {
    setSubheader(true)
  }
  const SetHeader_false = () => {
    setSubheader(false)
  }
  useEffect(() => {
    Router.events.on("routeChangeStart", BackDropOpen);
    Router.events.on("routeChangeComplete", BackDropClose);
    Router.events.on("routeChangeError", BackDropClose);
    setProgress(progress + 100)
     // check login credential
    setSubheader(false)
    try {
      if (localStorage.getItem('userid')) {
        setUserlogst(true);
        const usermobnow = localStorage.getItem('userid');
        const sendUser = { usermobnow }
        const data = fetch("/api/check", {
          method: "POST",
          headers: {
            'Content-type': 'application/json'
          },
          body: JSON.stringify(sendUser)
        }).then((a) => {
          return a.json();
        })
          .then((parsedUser) => {
            setUserlogData(parsedUser.data)
            

          })
       
      } else {
        setUserlogst(false);
      }
    } catch (error) {
      console.error(error)
      localStorage.clear()
    }
    // check login credential end

  }, [router.query]);
  
  

  return <>
    <Head>
      <title>Skillfilt Official Website</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/img/favicon.png" />
    </Head>
    <LoadingBar
      color='red'
      progress={progress}
      onLoaderFinished={() => setProgress(0)}
    />
    {subheader && (
      <SubNavbar handleOpen={handleOpen} userlogst={userlogst} userlogData={userlogData} />
    )}
    {!subheader && (
      <Navbar handleOpen={handleOpen} userlogst={userlogst}  />
    )}
   
  
   
    <Component {...pageProps} handleOpen={handleOpen} userlogst={userlogst} userlogData={userlogData} SetHeader_true={SetHeader_true} SetHeader_false={SetHeader_false} BackDropOpen={BackDropOpen} BackDropClose={BackDropClose} />
    <Login openModal={openModal} handleClose={handleClose} BackDropOpen={BackDropOpen} BackDropClose={BackDropClose} />
   
    <Backdropitem BackDropData={BackDropData} />
    <div className={styles.container_full} style={{ backgroundColor: '#232323' }} >
      <Footer />
    </div>
  </>
}

export default MyApp
