import React from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'

import Dashboardstyle from '../styles/Dashboard.module.css'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';
import { FiChevronRight, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from "react-icons/fi";
import Link from 'next/link'
const Account = () => {


    return (
        <>
            <Head>
                <title>About us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
               <div style={{padding:10}}>
                    <h3>About us</h3>

                    <p>SuperMarks offers industry-relevant Courses and Test Series to crack your Jobs with high performance and get succeeded in your Career. 👍</p>
               </div>


            </div>
        </>
    )
}

export default Account
