import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Jobs from '../components/Jobs'
const Careers = () => {
  return (<>
    <Head>
      <title>Careers : skillfilt.com</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/img/favicon.png" />
    </Head>
    <div className={styles.container}>
      <div className={styles.Careers}>
        <div className={styles.CareersTop}>
          <img src='https://aitechnolog.com/skillfilt/Storage/img/all/img-PVUE-About-Careers-GroupProfessionals-800x427.png' />
          <h2>We’re hiring across all disciplines, from operations to engineering.</h2>
        </div>

        <div className={styles.jobOpeningBox}>
          <Jobs/>
        </div>
      </div>
     
    </div>
    <div style={{ height: '150px' }}> </div>
  </>
  )
}

export default Careers