import { useState, useEffect, useContext } from 'react';
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'
import DbNavbar from '../components/Parts/DbNavbar'
import Image from 'next/image'
import CheckloginContext from '../context/auth/CheckloginContext'
import { FiFileText, FiHome, FiCheckSquare, FiUser, FiLogOut } from "react-icons/fi";
import { useRouter } from 'next/router'
import { BASE_URL, AppName } from '../Data/config'
import Link from 'next/link';
const Dashboard = () => {
    const router = useRouter()
    const Contextdata = useContext(CheckloginContext)
    const [isLoading, setIsLoading] = useState(true);
    useEffect(() => {
        if (Contextdata.IsLogin == true) {
            // console.log(Contextdata.Data)
            setIsLoading(false);
        } else {
            setIsLoading(true);
            router.push('/Login')
            // console.log('Not Login')
        }
    });
    const LogutNow = () => {
        localStorage.clear();
        router.push('/Login')
    };
    return (
        <><DbNavbar LogutNow={LogutNow} />

            <Head>
                <title>My Dashboard : {AppName}</title>
                <meta name="description" content="Generated by create next app" />

            </Head>
            {!isLoading &&
                <div className={styles.container}>
                    <div className={styles.DashboardBox}>
                        <div className={styles.Welcomeuserbox}>
                            <span>Hi👋 <b>{Contextdata.Data.name}</b></span>
                        </div>
                        <div className={styles.Countbox}>
                            <div className={styles.CountboxItem} style={{ backgroundColor: '#efecff' }}>
                                <div className={styles.CountboxItemText}>
                                    <small>Lavel</small>
                                    <span>10K+</span>
                                </div>
                                <div className={styles.CountboxItemImg}>
                                    <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/job.webp' height={75} width={75} />
                                </div>
                            </div>
                            <div className={styles.CountboxItem} style={{ backgroundColor: '#fff6e9' }}>
                                <div className={styles.CountboxItemText}>
                                    <small>Attempts</small>
                                    <span>30</span>
                                </div>
                                <div className={styles.CountboxItemImg}>
                                    <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/hiring.webp' height={75} width={75} />
                                </div>
                            </div>
                            <div className={styles.CountboxItem} style={{ backgroundColor: '#ffe9f1' }}>
                                <div className={styles.CountboxItemText}>
                                    <small>Points
                                    </small>
                                    <span>4000</span>
                                </div>
                                <div className={styles.CountboxItemImg}>
                                    <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/salary.webp' height={75} width={75} />
                                </div>
                            </div>
                            <div className={styles.CountboxItem} style={{ backgroundColor: '#dcf9fd' }}>
                                <div className={styles.CountboxItemText}>
                                    <small>Enrolled</small>
                                    <span>1</span>
                                </div>
                                <div className={styles.CountboxItemImg}>
                                    <Image src='https://aitechnolog.com/skillfilt/Storage/img/icons/worth.webp' height={75} width={75} />
                                </div>
                            </div>
                        </div>
                        <div className={styles.DashboardMenuBox}>
                            <Link href='/MyCourses'>
                                <div className={styles.DashboardMenuItem}>
                                    <div> <FiFileText /></div>
                                    <div style={{ marginLeft: '5px', marginTop: '-5px' }}> <span>My Courses</span></div>
                                </div>
                            </Link>
                            <Link href='/Mytest'>
                                <div className={styles.DashboardMenuItem}>
                                    <div> <FiFileText /></div>
                                    <div style={{ marginLeft: '5px', marginTop: '-5px' }}> <span>My Tests Series</span></div>
                                </div>
                            </Link>

                            <Link href='/MyAttempts'>
                                <div className={styles.DashboardMenuItem}>
                                    <div> <FiCheckSquare /></div>
                                    <div style={{ marginLeft: '5px', marginTop: '-5px' }}> <span>My Tests Attempts</span></div>
                                </div>
                            </Link>
                            <Link href='/MyAccount'>
                                <div className={styles.DashboardMenuItem}>
                                    <div> <FiUser /></div>
                                    <div style={{ marginLeft: '5px', marginTop: '-5px' }}> <span>My Account</span></div>
                                </div>
                            </Link>
                        </div>

                    </div>
                </div>
            }
        </>
    )
}

export default Dashboard
