import Head from 'next/head'

import styles from '../styles/Home.module.css'
import HeroboxNew from '../components/HeroboxNew'
import Footer from '../components/Footer'
import Proccesbox from '../components/Homepage/Proccesbox'
import NavbarNew from '../components/Parts/NavbarNew'

import CoursesHomelist from '../components/Homepage/CoursesHomelist'
import TestHomelist from '../components/Homepage/TestHomelist'
import Categorieshome from '../components/Categorieshome'
import Websitemenu from '../components/Websitemenu'
import WhyChoose from '../components/Homepage/WhyChoose'
import PassHeroBox from '../components/Homepage/PassHeroBox'
import { useState, useEffect } from 'react';
export default function Home() {

  return (
    <><NavbarNew />
      {/* <Websitemenu /> */}
      <Head>
        <title>Board Exam Official Website</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     
      <HeroboxNew />
      <div className={styles.dataspacer}> </div>
      <div className={styles.container_full} style={{ backgroundColor: '#efecff' }}>
        <Proccesbox />
      </div>
    
      <div className={styles.devider}> </div>
      <div className={styles.dataspacer}> </div>
      <div className={styles.container} >
        <CoursesHomelist />
      </div>
      
    
      {/* <div className={styles.container} >
        <TestHomelist />
        <div style={{ height: '50px' }}> </div>
      </div> */}
      
      <div style={{ height: '50px' }}> </div>
      <div className={styles.container_full} style={{ backgroundColor: '#efecff' }}>
        <div className={styles.container} >
          <WhyChoose />
        </div>
      </div>
      <div style={{ height: '30px' }}> </div>
      <div className={styles.container_full} style={{ backgroundColor: 'white' }}>
        <div className={styles.container} >
          <PassHeroBox />
        </div>
      </div>
      
      <div style={{ height: '100px' }}> </div>
      <div className={styles.container_full} style={{ backgroundColor: '#232323' }} >
        <Footer />
      </div>
    </>

  )
}
