import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Herobox from '../components/Herobox'
import Footer from '../components/Footer'
import Proccesbox from '../components/Proccesbox'

import TestHomelist from '../components/TestHomelist'
import Caterorieshome from '../components/Caterorieshome'

import { useState, useEffect } from 'react';
export default function Home({ SetHeader_false }) {
  useEffect(() => {
    SetHeader_false()
  })
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Board Exam Official Website</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Herobox />
        <div className={styles.dataspacer}> </div>
      </div>
      
      <div className={styles.dataspacer}> </div>
      <div className={styles.container_full} style={{ backgroundColor: '#efecff' }}>
        <Proccesbox />
      </div>
    
      <div className={styles.devider}> </div>
      <div className={styles.dataspacer}> </div>
      <div className={styles.container} >
        <TestHomelist />
        <Caterorieshome />
      </div>
      
      
      <div style={{ height: '100px' }}> </div>
      <div className={styles.container_full} style={{ backgroundColor: '#232323' }} >
        <Footer />
      </div>
    </>

  )
}
