import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Herobox from '../components/Herobox'
import BannerSlider from '../components/BannerSlider'
import Categoriesslider from '../components/Categorieshome'
import Testserieshome from '../components/Testserieshome'
import { useState, useEffect } from 'react';
export default function Home({ SetHeader_false }) {
  useEffect(() => {
    SetHeader_false()
  })
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
         
        </Head>
        <Herobox />
        <div style={{ height: '50px' }}> </div>
        <BannerSlider />
      </div>
      <div style={{ height: '50px' }}> </div>
      <div className={styles.container}>
        <Testserieshome />
        <div style={{ height: '50px' }}> </div>
        <Categoriesslider />
      </div>
    </>

  )
}
