import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Loginstyles from '../styles/Login.module.css'
import TextField from '@mui/material/TextField';
import { FiChevronRight } from 'react-icons/fi';
const Login = () => {
  return (
      <>
          <Head>
              <title>Login</title>
              <meta name="description" content="Generated by create next app" />
          </Head>

          <div className={styles.container_full}>
              <div className={Loginstyles.LoginBox}>
                  <div className={Loginstyles.LoginBoxItem}>
                      <h1>Welcome to the Skillfilt</h1>
                      <span>Please login to our account</span>
                      <div className={Loginstyles.LoginBox_input}>
                          <TextField fullWidth label="Enter Mobile Number" id="fullWidth" />
                      </div>
                      <div style={{ height: '20px' }}> </div>
                      <div className={styles.Btn_icon}>
                          <small>Get OTP</small>
                          <span><FiChevronRight /></span>
                      </div>
                      <div style={{ height: '5px' }}> </div>
                      <small>By signing up, you agree to our <span className={styles.url}>Terms of use</span> and <span className={styles.url}>Privacy Policy</span></small>
                  </div>
              </div>
          </div>
      </>
  )
}

export default Login