import { useState, useEffect } from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { FiChevronRight, FiNavigation, FiInfo, FiCoffee, FiFileText, FiClock, FiUnlock, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from 'react-icons/fi';
import SecondHeader from '../components/SecondHeader'
import Link from 'next/link'
import Navbar from '../components/Navbar'
const Mytest = () => {
  const [isLoading, setIsLoading] = useState(true);
  const router = useRouter()
  const [Retdata, setRetdata] = useState([]);
  useEffect(() => {

    try {
      if (localStorage.getItem('userid')) {

        const usermobnow = localStorage.getItem('userid');
        const userid = { usermobnow }
        const data = fetch("/api/MyAttemptslist", {
          method: "POST",
          headers: {
            'Content-type': 'application/json'
          },
          body: JSON.stringify(userid)
        }).then((a) => {
          return a.json();
        })
          .then((parsedUser) => {
            setRetdata(parsedUser)
            setIsLoading(false);
          })

      } else {

      }
    } catch (error) {
      console.error(error)


    }
    // check login credential end

  }, [router.query]);


  return (
    <>
      <Navbar />
      <Head>
        <title>My Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SecondHeader Title={'My Test Attempts '} />
      <div className={styles.container}>

        <div className={styles.DashboardBox}>
          {isLoading &&
            <div>
              <div style={{ marginTop: '15px' }}>
                <Skeleton variant="rectangular" height={100} />
              </div>
              <div style={{ marginTop: '15px' }}>
                <Skeleton variant="rectangular" height={100} />
              </div>
              <div style={{ marginTop: '15px' }}>
                <Skeleton variant="rectangular" height={100} />
              </div>
              <div style={{ marginTop: '15px' }}>
                <Skeleton variant="rectangular" height={100} />
              </div>
              <div style={{ marginTop: '15px' }}>
                <Skeleton variant="rectangular" height={100} />
              </div>
            </div>
          }
          {!isLoading &&
            <div>
              <div className={styles.Welcomeuserbox}>
                <span>My Attempts List ({Retdata.length})</span>
              </div>

              {Retdata.map((item) => {
                return <div className={styles.testboxtestlist} key={item.id}>
                  <div className={styles.testboxtestlistA} >
                    <div className={styles.Testlistitem}>

                      <div className={styles.Testlistitems}>

                        <div> <span style={{ fontWeight: '500'}}>#{item.attemptid}</span> <span>{item.Title}</span></div>
                        <div className={styles.testiconsBox}>
                          <div className={styles.testiconsItemMain}>
                            <span><FiClock /></span>   <span>{item.date}</span>
                          </div>
                          <div className={styles.testiconsItemMain}>
                            <span><FiCoffee /></span>   <span>{item.statusText}</span>
                          </div>

                        </div>
                      </div>

                      <Link href={`/AttemptResult/${item.attemptid}`}>
                        <div className={styles.Btn_icon}>
                          <span><FiChevronRight /></span>
                          <small>Result</small>

                        </div>
                      </Link>

                    </div>


                  </div>

                </div>
              }

              )}
            </div>
          }
        </div>
      </div>
    </>
  )
}

export default Mytest
