import { useState, useEffect, useContext } from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { FiChevronRight, FiNavigation, FiInfo, FiCoffee, FiFileText, FiClock, FiUnlock, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from 'react-icons/fi';
import SecondHeader from '../components/SecondHeader'
import CheckloginContext from '../context/auth/CheckloginContext'
import Link from 'next/link'
import DbNavbar from '../components/Parts/DbNavbar'
const MyCourses = () => {
    const [isLoading, setIsLoading] = useState(true);
    const router = useRouter()
    const [Retdata, setRetdata] = useState([]);

    const Contextdata = useContext(CheckloginContext)
   
    useEffect(() => {

        if (Contextdata.IsLogin == true) {
            const usermobnow = localStorage.getItem('userid');
            const userid = { usermobnow }
            const data = fetch("/api/GetMYCourses", {
                method: "POST",
                headers: {
                    'Content-type': 'application/json'
                },
                body: JSON.stringify(userid)
            }).then((a) => {
                return a.json();
            })
                .then((parsedUser) => {

                    setRetdata(parsedUser)
                    setIsLoading(false);
                })
        } else {
            setIsLoading(true);
            router.push('/Login')
        }
    }, [router.query]);


    return (
        <>
            <DbNavbar />
            <Head>
                <title>Courses :{Contextdata.Data.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
          
            <div className={styles.container}>

                <div className={styles.DashboardBox}>
                    {isLoading &&
                        <div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                            <div style={{ marginTop: '15px' }}>
                                <Skeleton variant="rectangular" height={100} />
                            </div>
                        </div>
                    }
                    {!isLoading &&
                        <div>
                            <div className={styles.Welcomeuserbox}>
                                <span>Active Courses  ({Retdata.length})</span>
                            </div>

                            {Retdata.map((item) => {
                                return <div className={styles.testboxtestlist} key={item.id}>
                                    <div className={styles.testboxtestlistA} >
                                        <div className={styles.Testlistitem}>

                                            <div className={styles.Testlistitems}>

                                                <div> <h4 style={{margin:'0'}}>{item.Title}</h4></div>
                                                <div className={styles.testiconsBox}>
                                                    <div className={styles.testiconsItemMain}>
                                                        <span><FiCoffee /></span>   <span>{item.statusText}</span>
                                                    </div>
                                                    <div className={styles.testiconsItemMain}>
                                                        <span><FiFileText /></span>   <span>Valid till : {item.Endvalidity_date}</span>
                                                    </div>
                                                   
                                                </div>
                                            </div>

                                            <Link href={`/ClassRoom/${item.pid}`} style={{ textDecoration: 'none'}}>
                                                <div className={styles.Btn_icon}>
                                                    <span><FiChevronRight /></span>
                                                    <small>Enter</small>

                                                </div>
                                            </Link>

                                        </div>


                                    </div>

                                </div>
                            }

                            )}
                        </div>
                    }
                </div>
            </div>
        </>
    )
}

export default MyCourses
