import React from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'

import Myorderslist from '../components/Myorderslist'
import Dashboardstyle from '../styles/Dashboard.module.css'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';
import { FiChevronRight, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from "react-icons/fi";
import Link from 'next/link'
const MyOrders = () => {


    return (
        <>
            <Head>
                <title>My Orders</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Myorderslist />
        </>
    )
}

export default MyOrders
