import React from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'

import Dashboardstyle from '../styles/Dashboard.module.css'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';
import { FiChevronRight, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from "react-icons/fi";
import Link from 'next/link'
const Account = () => {


    return (
        <>
            <Head>
                <title>Refund Policy</title>
                <meta name="description" content="Generated by create next app" />
                
            </Head>

            <div className={styles.container} style={{ padding: 10 }}>
                <h3>Returns & Refund Policy</h3>
                
                <p>Since we all deal in online video courses/classes and it&rsquo;s a digital online service, we don&rsquo;t offer refund, unfortunately we can&rsquo;t offer you a refund or exchange. We request you to watch our sample free videos, available in almost every course. You can also watch our youtube channel videos to get to know about quality of our videos.</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Refunds (if applicable)</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; We don&rsquo;t except refund request Late or missing refunds (if applicable) Because of digital goods and services ,we don&rsquo;t except refund requests, please contact us at contact@rkcodingclasses.com.</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Sale items (if applicable)</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Sale items cannot be refunded.</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Exchanges (if applicable)</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Since every shared course is in itself a valuable property, we don&rsquo;t take exchange requests too.</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Shipping</p>

                <p>&nbsp;</p>

                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; On our website, everything is online. We don&rsquo;t provide CD or DVD.</p>


            </div>
        </>
    )
}

export default Account
