import React from 'react'
import Head from 'next/head'
import Skeleton from '@mui/material/Skeleton';
import styles from '../styles/Home.module.css'

import Dashboardstyle from '../styles/Dashboard.module.css'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';
import { FiChevronRight, FiShoppingBag, FiMapPin, FiCreditCard, FiLogOut } from "react-icons/fi";
import Link from 'next/link'
const Account = () => {


    return (
        <>
            <Head>
                <title>Shipping and Delivery</title>
                <meta name="description" content="Generated by create next app" />
                
            </Head>

            <div className={styles.container} style={{ padding: 10 }}>
                <h3>Shipping and Delivery</h3>
                <p>Currentry we are not delivering any physical packages.</p>

            </div>
        </>
    )
}

export default Account
